name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before submitting your issue, please make
        sure you are using the latest version of the charm. If not, please switch to this image prior to 
        posting your report to make sure it's not already solved.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: >
        If applicable, add screenshots to help explain the problem you are facing.
    validations:
      required: true
