apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: spark-workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spark-workloads
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spark-workloads
subjects:
- kind: ServiceAccount
  name: spark-sa
  namespace: spark-workloads
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-worker-pod-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status", "events"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-scheduler-pod-manager
subjects:
- kind: ServiceAccount
  name: airflow-scheduler-k8s
  namespace: __MODEL_NS__
roleRef:
  kind: ClusterRole
  name: airflow-worker-pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-executor-pod-manager
subjects:
- kind: ServiceAccount
  name: airflow-kubernetes-executor-k8s
  namespace: __MODEL_NS__
roleRef:
  kind: ClusterRole
  name: airflow-worker-pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-sa-spark-workloads
subjects:
- kind: ServiceAccount
  name: default
  namespace: __MODEL_NS__
roleRef:
  kind: ClusterRole
  name: airflow-worker-pod-creator
  apiGroup: rbac.authorization.k8s.io
