set export # Just variables are exported to environment variables

[private]
default:
	just --list

install-nginx-controller:
	#!/usr/bin/bash
	set -euxo pipefail

	if [ "$(kubectl get ingressclass | grep nginx | wc -l)" = "1" ]; then
		echo "nginx ingress controller already installed"
		exit 0
	fi

	kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/tags/controller-v1.13.3/deploy/static/provider/cloud/deploy.yaml

	until [[ $(kubectl -n ingress-nginx get svc | grep -E 'ingress-nginx-controller\s' | awk '{print $4}') =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] ; do
		echo "Waiting for ingress controller to be assigned an external ip"
		sleep 5
	done

[private]
stop-local-registry:
	docker stop registry || true
	docker rm registry || true

[private]
start-local-registry:
	docker start registry || docker run -d -p 5000:5000 --name registry registry:2.7

[private]
push-to-local-registry rock_filepath registry tag: (start-local-registry)
	rockcraft.skopeo --insecure-policy copy --dest-tls-verify=false \
		"oci-archive:${rock_filepath}" \
		"docker://localhost:5000/${registry}:${tag}"

# Print commands to install dependencies
install-dependencies confirm="false":
	#!/usr/bin/bash

	if [[ "${confirm}" == "false" ]]; then
		echo "Please run target with confirmation of dangerous actions"
		exit 1;
	fi

	sudo apt-get purge $(dpkg -l | grep -i docker | awk '{print $2}')
	sudo apt-get purge containerd.io
	sudo rm -r /run/containerd

	sudo -E concierge prepare -p k8s --extra-snaps=terraform,just

	sudo snap install docker
	sudo snap start docker

# Set up environment to enable Temporal deployment
set-up-environment:
	#!/usr/bin/bash
	set -euxo pipefail

	sudo k8s set load-balancer.l2-mode=true load-balancer.cidrs=10.2.0.0/24
	sudo k8s enable ingress load-balancer

	sudo k8s kubectl config view --raw | tee ~/.kube/config > /dev/null

	just install-nginx-controller

# Build sample python and go worker images
prepare-worker-images: (start-local-registry)
	#!/usr/bin/bash
	set -euxo pipefail

	cd worker_python && rockcraft pack
	just push-to-local-registry $(ls -d "$PWD"/* | grep "\.rock") worker-python dev

	cd ../worker_go && rockcraft pack
	just push-to-local-registry $(ls -d "$PWD"/* | grep "\.rock") worker-go dev

# Initialize the terraform project
init-terraform force="false":
	#!/usr/bin/bash
	cd terraform
	if [[ "${force}" != "false" || ! -d ".terraform" ]]; then
		terraform init
	else
		echo "terraform already initialized"
	fi

# Clean up, including removing existing juju models
destroy:
	#!/usr/bin/bash
	juju destroy-model --force --destroy-storage --no-prompt temporal-server
	juju destroy-model --force --destroy-storage --no-prompt temporal-worker
	juju destroy-model --force --destroy-storage --no-prompt cos-lite

	rm -f terraform/terraform.tfstate*

# Format the Charmed Temporal solution + COS with terraform
format:
	#!/usr/bin/bash
	set -euxo pipefail

	cd terraform/
	terraform fmt
	tflint --chdir .

# Plan the Charmed Temporal solution + COS with terraform
plan-temporal-solution:
	#!/usr/bin/bash
	set -euxo pipefail

	cd terraform/
	terraform plan

# Build worker images and push them to local registry
build-and-push-images:
	#!/usr/bin/bash
	set -x

	cd worker_python && rockcraft pack

	cd ../worker_go && rockcraft pack

	cd ..

	worker_python_rock_filepath=$(ls -d "$PWD"/worker_python/* | grep "\.rock")
	worker_go_rock_filepath=$(ls -d "$PWD"/worker_go/* | grep "\.rock")

	just stop-local-registry
	just push-to-local-registry ${worker_python_rock_filepath} worker-python dev
	just push-to-local-registry ${worker_go_rock_filepath} worker-go dev

# Apply the Charmed Temporal solution + COS with terraform
apply-temporal-solution:
	#!/usr/bin/bash
	set -euxo pipefail

	controller=$(echo "k8s")
	
	juju switch ${controller}

	cd terraform/

	rm -f inputs.tfvars

	controller_addresses=$(juju show-controller --format json | jq -r ".\"${controller}\".details.\"api-endpoints\"[0]")
	password=$(juju show-controller --format json --show-password | jq -r ".\"${controller}\".account.password")
	juju show-controller --format json | jq -r ".\"${controller}\".details.\"ca-cert\"" > ./ca-cert.pem

	echo "controller_addresses = \"${controller_addresses}\"" > inputs.tfvars
	echo "password = \"${password}\"" >> inputs.tfvars

	terraform apply -auto-approve -var-file=inputs.tfvars

update-worker-image-resources:
	#!/usr/bin/bash
	juju refresh --model temporal-worker worker-go --resource temporal-worker-image="localhost:5000/worker-go:dev"

	juju refresh --model temporal-worker worker-python --resource temporal-worker-image="localhost:5000/worker-python:dev"
